// Generated by gencpp from file perception_stack_pkg/DetectionList.msg
// DO NOT EDIT!


#ifndef PERCEPTION_STACK_PKG_MESSAGE_DETECTIONLIST_H
#define PERCEPTION_STACK_PKG_MESSAGE_DETECTIONLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <perception_stack_pkg/BoundingBox.h>

namespace perception_stack_pkg
{
template <class ContainerAllocator>
struct DetectionList_
{
  typedef DetectionList_<ContainerAllocator> Type;

  DetectionList_()
    : header()
    , frame_id(0)
    , detections()  {
    }
  DetectionList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frame_id(0)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _frame_id_type;
  _frame_id_type frame_id;

   typedef std::vector< ::perception_stack_pkg::BoundingBox_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::perception_stack_pkg::BoundingBox_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::perception_stack_pkg::DetectionList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_stack_pkg::DetectionList_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionList_

typedef ::perception_stack_pkg::DetectionList_<std::allocator<void> > DetectionList;

typedef boost::shared_ptr< ::perception_stack_pkg::DetectionList > DetectionListPtr;
typedef boost::shared_ptr< ::perception_stack_pkg::DetectionList const> DetectionListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_stack_pkg::DetectionList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_stack_pkg::DetectionList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception_stack_pkg::DetectionList_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::DetectionList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.frame_id == rhs.frame_id &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception_stack_pkg::DetectionList_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::DetectionList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception_stack_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::DetectionList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::DetectionList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::DetectionList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::DetectionList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::DetectionList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::DetectionList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_stack_pkg::DetectionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f7c56c637c85f5556d0300fcb83a605";
  }

  static const char* value(const ::perception_stack_pkg::DetectionList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f7c56c637c85f55ULL;
  static const uint64_t static_value2 = 0x56d0300fcb83a605ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_stack_pkg::DetectionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_stack_pkg/DetectionList";
  }

  static const char* value(const ::perception_stack_pkg::DetectionList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_stack_pkg::DetectionList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 frame_id\n"
"BoundingBox[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: perception_stack_pkg/BoundingBox\n"
"int32 x1\n"
"int32 y1\n"
"int32 x2\n"
"int32 y2\n"
"float32 confidence\n"
"string class_name\n"
"int32 class_id\n"
"int32 x\n"
"int32 y\n"
"int32 width\n"
"int32 height\n"
"\n"
;
  }

  static const char* value(const ::perception_stack_pkg::DetectionList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_stack_pkg::DetectionList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frame_id);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_stack_pkg::DetectionList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_stack_pkg::DetectionList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frame_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frame_id);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_stack_pkg::BoundingBox_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_STACK_PKG_MESSAGE_DETECTIONLIST_H
