// Generated by gencpp from file perception_stack_pkg/HumanReadableObject.msg
// DO NOT EDIT!


#ifndef PERCEPTION_STACK_PKG_MESSAGE_HUMANREADABLEOBJECT_H
#define PERCEPTION_STACK_PKG_MESSAGE_HUMANREADABLEOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace perception_stack_pkg
{
template <class ContainerAllocator>
struct HumanReadableObject_
{
  typedef HumanReadableObject_<ContainerAllocator> Type;

  HumanReadableObject_()
    : class_name()
    , speed(0.0)
    , direction()
    , position()  {
    }
  HumanReadableObject_(const ContainerAllocator& _alloc)
    : class_name(_alloc)
    , speed(0.0)
    , direction(_alloc)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef float _speed_type;
  _speed_type speed;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> const> ConstPtr;

}; // struct HumanReadableObject_

typedef ::perception_stack_pkg::HumanReadableObject_<std::allocator<void> > HumanReadableObject;

typedef boost::shared_ptr< ::perception_stack_pkg::HumanReadableObject > HumanReadableObjectPtr;
typedef boost::shared_ptr< ::perception_stack_pkg::HumanReadableObject const> HumanReadableObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator2> & rhs)
{
  return lhs.class_name == rhs.class_name &&
    lhs.speed == rhs.speed &&
    lhs.direction == rhs.direction &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception_stack_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9f70d272b495eeb16fc86a8a12ccddd";
  }

  static const char* value(const ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9f70d272b495eebULL;
  static const uint64_t static_value2 = 0x16fc86a8a12ccdddULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_stack_pkg/HumanReadableObject";
  }

  static const char* value(const ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string class_name\n"
"float32 speed\n"
"string direction\n"
"geometry_msgs/Point position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_name);
      stream.next(m.speed);
      stream.next(m.direction);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HumanReadableObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_stack_pkg::HumanReadableObject_<ContainerAllocator>& v)
  {
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_STACK_PKG_MESSAGE_HUMANREADABLEOBJECT_H
